name: Trigger Cloud Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to /run endpoint
        run: |
          curl -X POST https://cloud-scraper-project.onrender.com/run
